---
site:
  title: "Ansible Network Automation Workshop"
  url: https://rhpds.github.io/zt-network-automation-workshop/
  start_page: modules::index.adoc

asciidoc:
  attributes:
    lab_name: "Ansible Network Automation Workshop"
    release-version: master
    page-pagination: true

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

antora:
  extensions:
    - require: ./content/lib/dev-mode.js
      enabled: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
