---

antora:
  name: modules
  dir: www
  modules:
    - name: 03-module-01-explore-lab
      label: "Module 1: Explore the lab environment"
    - name: 04-module-02-first-playbook
      label: "Module 2: First Ansible Playbook"
    - name: 05-module-03-facts
      label: "Module 3: Ansible facts"
    - name: 06-module-04-resource-modules
      label: "Module 4: Resource modules"
    - name: 07-module-05-explore-controller
      label: "Module 5: Explore Automation controller"
    - name: 08-module-06-job-template
      label: "Module 6: Job templates"
    - name: 09-module-07-survey
      label: "Module 7: Surveys"
    - name: 10-module-08-rbac
      label: "Module 8: RBAC"
    - name: 11-module-09-workflow
      label: "Module 9: Workflows"

tabs:
  - name: ">_ terminal"
    url: /wetty/root/ssh/containerlab/
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
    external: false
