---
# By default egress traffic is not allowed, define below the ports allowed.
ingress:
- ports:
  - protocol: TCP
    port: 2222
  - protocol: TCP
    port: 2223
  - protocol: TCP
    port: 2224
  - protocol: TCP
    port: 2225
  - protocol: TCP
    port: 2226
  - protocol: TCP
    port: 2227
  - protocol: TCP
    port: 2228
  - protocol: TCP
    port: 8181
  - protocol: TCP
    port: 8282
  - protocol: TCP
    port: 8383
  - protocol: TCP
    port: 8484
  - from:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
egress:
  - ports:
      - protocol: TCP
        port: 443
  - to:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
