---
ansible-navigator:
  ansible:
    inventory:
      entries:
      - /home/rhel/network-workshop/lab_inventory/hosts

  execution-environment:
    image: quay.io/rhpds/summit-2026-acme-corp-network-ee:summit-2026
    enabled: true
    container-engine: podman
    pull:
      policy: missing
